// Code generated by MockGen. DO NOT EDIT.
// Source: msgcat.go

// Package mock_msgcat is a generated GoMock package.
package mock_msgcat

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	msgcat "github.com/loopcontext/msgcat"
	reflect "reflect"
)

// MockMessageCatalog is a mock of MessageCatalog interface
type MockMessageCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockMessageCatalogMockRecorder
}

// MockMessageCatalogMockRecorder is the mock recorder for MockMessageCatalog
type MockMessageCatalogMockRecorder struct {
	mock *MockMessageCatalog
}

// NewMockMessageCatalog creates a new mock instance
func NewMockMessageCatalog(ctrl *gomock.Controller) *MockMessageCatalog {
	mock := &MockMessageCatalog{ctrl: ctrl}
	mock.recorder = &MockMessageCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageCatalog) EXPECT() *MockMessageCatalogMockRecorder {
	return m.recorder
}

// LoadMessages mocks base method
func (m *MockMessageCatalog) LoadMessages(lang string, messages []msgcat.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadMessages", lang, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadMessages indicates an expected call of LoadMessages
func (mr *MockMessageCatalogMockRecorder) LoadMessages(lang, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadMessages", reflect.TypeOf((*MockMessageCatalog)(nil).LoadMessages), lang, messages)
}

// GetMessageWithCtx mocks base method
func (m *MockMessageCatalog) GetMessageWithCtx(ctx context.Context, msgKey string, params msgcat.Params) *msgcat.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageWithCtx", ctx, msgKey, params)
	ret0, _ := ret[0].(*msgcat.Message)
	return ret0
}

// GetMessageWithCtx indicates an expected call of GetMessageWithCtx
func (mr *MockMessageCatalogMockRecorder) GetMessageWithCtx(ctx, msgKey, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageWithCtx", reflect.TypeOf((*MockMessageCatalog)(nil).GetMessageWithCtx), ctx, msgKey, params)
}

// WrapErrorWithCtx mocks base method
func (m *MockMessageCatalog) WrapErrorWithCtx(ctx context.Context, err error, msgKey string, params msgcat.Params) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WrapErrorWithCtx", ctx, err, msgKey, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// WrapErrorWithCtx indicates an expected call of WrapErrorWithCtx
func (mr *MockMessageCatalogMockRecorder) WrapErrorWithCtx(ctx, err, msgKey, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WrapErrorWithCtx", reflect.TypeOf((*MockMessageCatalog)(nil).WrapErrorWithCtx), ctx, err, msgKey, params)
}

// GetErrorWithCtx mocks base method
func (m *MockMessageCatalog) GetErrorWithCtx(ctx context.Context, msgKey string, params msgcat.Params) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorWithCtx", ctx, msgKey, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetErrorWithCtx indicates an expected call of GetErrorWithCtx
func (mr *MockMessageCatalogMockRecorder) GetErrorWithCtx(ctx, msgKey, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorWithCtx", reflect.TypeOf((*MockMessageCatalog)(nil).GetErrorWithCtx), ctx, msgKey, params)
}
